name: Versioning

on:
  push:
    branches:
      - master
      - develop
      - feature/*

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.11
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.11

      - name: Update version.txt
        run: echo "${{ steps.gitversion.outputs.fullSemVer }}" > version.txt

      - name: Update csproj version
        run: |
          sed -i 's|<Version>.*</Version>|<Version>${{ steps.gitversion.outputs.fullSemVer }}</Version>|g' **/*.csproj

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add version.txt **/*.csproj
          git commit -m "Update version to ${{ steps.gitversion.outputs.fullSemVer }}" || echo "No changes to commit"
          git push
